#!/bin/sh
term="st"
[ "$1" != "" ] && term="$1"
[ "$term" = "st" ] && st -e "bash -c 'echo +++++++++++ | unimatrix'" && wmctrl -b st -r add,fullscreen
[ "$term" = "konsole" ] && konsole --fullscreen --profile='video playing' -e "bash -c 'echo +++++++++++ | unimatrix'"
[ "$term" = "gnome-terminal" ] && gnome-terminal --full-screen -e "bash -c 'echo +++++++++++ | unimatrix'"
