#!/usr/bin/env python3
import os
rows, columns = os.popen('stty size', 'r').read().split()
rows, columns = (int(rows), int(columns))

colors=[[160, 202, 226, 28, 27, 53], 
        [39, 207, 231, 207, 39], 
        [162, 162, 60, 55, 55]]
buf=[""]*rows
lenght=int(columns/len(colors))

for (ng, flag) in enumerate(colors):
    for (n, color) in enumerate(flag):
        for line in range(int(rows/len(flag))):
            buf[n*int(rows/len(flag))+line]+="\x1b[48;5;"+str(color)+"m"+" "*lenght+"\x1b[m";
        for (nl, line) in enumerate(buf):
            if(len(line)<ng*lenght):
                buf[nl]+=(ng*lenght-len(line))*" "

[print(i) for i in buf]
