#!/bin/bash
file="$(mktemp)"
chmod +x "$file"

# -- ARGS
b=0
w=0
k=0
while getopts ":b:w:k" opt; do
case ${opt} in
    b ) # process option g
      b=$OPTARG;;
    w )
      w=$OPTARG;;
    k )
      k=1;;
    \? ) # Extra flags
      echo "Usage: queue [-b prepend] [-w duration] < commands">/dev/stderr && exit;;
  esac
done
shift $((OPTIND -1))

# -- RUN
read c
while [ "$c" != "" ]
do
	[ "$b" = 0 ] && echo "$c" >>"$file"
	[ "$b" != 0 ] && echo "$b $c" >>"$file"
	[ "$w" != "0" ] && echo "sleep $w" >>"$file"
	read c
done
"$file"
[ "$k" = 0 ] && rm "$file"
[ "$k" = 0 ] || echo "$file"
