#!/usr/bin/env python3

import subprocess
import os
import sys

print("This changes the scripts based on your shell.")
print("which shell are you using?")
shell=input()
path=os.path.dirname(sys.argv[0])
file=open(path+"/nope", "w")

# ---------- bash
if(shell == "bash"):
	file.write("""#!
while true
do
    sleep 0.2 # When the file is created the permissions may not be set up, so wait.
    dir=$(inotifywait -e create . | sed -r 's/^.*CREATE(,ISDIR)*\s+(.*)$/\\2/ig')
    type=$(file $file | sed 's/^.*: //')
    [ "$type" = "directory" ] && cd $file && exit
    [ "$type" = "" ] && continue 
    [ "$type" = "directory" ] || xdg-open $file && exit
done
exit
""")

# ---------- fish

if(shell == "fish"):
	file.write("""#!
while true
    sleep 0.2 # When the file is created the permissions may not be set up, so wait.
    set file (inotifywait -e create . | sed -r 's/^.*CREATE(,ISDIR)*\s+(.*)$/\\2/ig')
    set type (file $file | sed 's/^.*: //')
    [ "$type" = "directory" ] && cd $file && exit
    [ "$type" = "" ] && continue 
    [ "$type" = "directory" ] || xdg-open $file && exit
end
exit
""")

subprocess.Popen(['chmod', '+x', path+'nope'])
