#!/bin/sh

trap "{ exit 255; }" INT TERM EXIT

# -- VARS
dur=30

# -- ARGS
g=0
flags=""
[ "$1" = "" ] && echo "Usage: tct [-g] [MPV flags] \"file\"">/proc/self/fd/2 && exit
while getopts "g" opt; do
case ${opt} in
    g ) # process option g
      g=1;;
    \? ) # Extra flags
      flags="$flags $OPTARG";;
  esac
done
shift $((OPTIND -1))
[ "$g" = 0 ] && flags="$flags -vo=tct"

# -- RUN
PLAYING=1
while [ $PLAYING -ne 0 ]; 
do 
	qdbus org.freedesktop.ScreenSaver /ScreenSaver SimulateUserActivity
	sleep $dur
	PLAYING=$(pgrep -fc "mpv --no-config .*")
done &
mpv --no-config "$vid" $flags --profile=sw-fast --vo-tct-height=54 2>/dev/null
