#!/bin/bash

# -- ARGS
flags=""
g=0
d=0
flags=""
while getopts "gd" opt; do
echo $opt
case ${opt} in
    g ) g=1;;
    d ) d=1;;
    \? ) flags="$flags $OPTARG";;
esac
done
echo $g

# -- RUN
vurl=$1
vfile=$vurl
[ $d = 1 ] && tdir=$(mktemp -d) && cd $tdir && vfile=$tdir/`youtube-dl --exec "echo {}" $vurl -q`
[ $g = 1 ] && flags="-g --fs"
tct "$vfile" $flags
